import { CategorySchema } from '@/zod/schemas/shopApiSchema';

describe('CategorySchema', () => {
  it('accepts with optional parentId', () => {
    const a = { id: 10, name: 'Cat', autogeneratedSlug: 'cat' };
    const b = { id: 11, name: 'Sub', autogeneratedSlug: 'sub', parentId: 10 };
    expect(() => CategorySchema.parse(a)).not.toThrow();
    expect(() => CategorySchema.parse(b)).not.toThrow();
  });
});
